# Server
server.port=${PORT:8080}

# MySQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Anthropic API Key
gemini.api.key=AIzaSyB6F7Zgmb-nZQ2Jt-QDf4CQqH-RDMuR8Zo
