# Server
server.port=${5000}

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/stockwise
spring.datasource.username=root
spring.datasource.password=srivardhan888
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Anthropic API Key
gemini.api.key=AIzaSyB6F7Zgmb-nZQ2Jt-QDf4CQqH-RDMuR8Zo
